#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server:

#check if all the requirement are passed
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
# Assign the command line argument
	
	path_to_file=$1 
	ip_address=$2
	username=$3 
	path_to_ssh_key=$4

# Transfer the file using scp
	scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip_address":~
fi
