#!/usr/bin/env bash
# bash script that Installs Nginx with the following configurations:
#    Listens on port 80.
#    Returns a page containing "Hello World" when queried
#    at the root with a curl GET request.

# update and Install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# configure Nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'

# Creat sample page
echo "Hello World!" > /var/www/html/index.html

# Start Nginx
service nginx start

