#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# The redirection must be a “301 Moved Permanently”

# update and install ngingx
sudo apt-get update
sudo apt-get install -y nginx

# creating sample page 
echo "Hello World!" > /var/www/html/index.html

# adding  configuration to the existing server block
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart
