#!/usr/bin/env bash
#A script that print "best school" 10 times,it print "Hi" at the 9th iteration

count=0

while [ "$count" -le 10 ]
do
	echo "Best School"
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	(( count++ ))
done
