#!/usr/bin/env bash
# A script that print "Best School" 10 times with some exception"

i=0

while [ $i -le 10 ]
do	
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif
	[ $i -le 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
