#!/usr/bin/env bash

#change nginx user in the nginx conf
sed -i 's/user www-data;/user nginx/' /etc/nginx/nginx.conf

# configure nginx to listening on all active IPs on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

#change ownership of nginx directory to user
chmod 644 /etc/nginx/nginx.conf

#kill apache to avaoid interuption with nginx
pkill apache2

#start nginx
sudo -u nginx service nginx start
